### ISSUE TITLE
Team Description

### ISSUE THREAD

**Issue by AbelG101** [PRATAP-KUMAR/react-group-project#25]
## React group project
- We are a team of two:
    - @PRATAP-KUMAR 
    - @AbelG101 
    - @uisendy 
- [Here's the link](https://github.com/PRATAP-KUMAR/react-group-project/projects/3) to our project setup (kanban board).

**Comment by phelian23** [comment]
Hi @Team,

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Highlights
Kanban template copied properly 👍
Kanban card set up properly 👍
Good issue description 👍

## Required Changes ♻️

- [ ] Good job setting up the kanban board, however, you need to assign the tasks to team members equally. presently, the tasks are not assigned. kindly the tasks.

_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by phelian23** [comment]
Hi @Team,

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 


![68747470733a2f2f6d65646961322e67697068792e636f6d2f6d656469612f5061536e555a573145657970756c734f77642f67697068792e676966](https://user-images.githubusercontent.com/85095702/192231465-c7e93be3-bc58-4972-85bd-c06fcc16806e.gif)

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
